sfa integrated
zyplai/scoring_pipeline pull request #12
Opened 2023-11-14 11:40 UTC by beckortikov

1. sfa.py moved to features module
1. added method run_sfa in commands
2. sfa store results then return its output

2023-11-14 13:46 UTC, rufmus23 requested changes

2023-11-14 13:46 UTC, rufmus23 commented on features/sfa.py
> +            model = cb_model.fit(X_train,
В if else должно быть только cat_features, а .fit уже за пределами if else

2023-11-14 13:46 UTC, rufmus23 commented on features/sfa.py
> +        try:
Лучше сделать в data еще одну папку - sfa_results и в ней папки с отдельными прогонами/версиями. Плюс если мы сохраняем с current_datetime, а не названием версии, то нужно конфиг тоже туда сохранять в каждую папку с версиями.

2023-11-14 17:13 UTC, kshurik submitted a review, later dismissed

2023-11-14 17:13 UTC, kshurik commented on commands.py
> +    print(sfa.get_sfa_results())
print() не нужен тут -- результаты должны сохраняться

2023-11-14 17:49 UTC, beckortikov commented on features/sfa.py
> +        try:
хранения configa надо внести изменения в utils, чтобы save_txt создать, остальные изменения сделал прими это пр, потом пр сделаю с utils, потом конфиг сохраню в тхт внутри sfa_result

2023-11-14 17:49 UTC, beckortikov commented on commands.py
> +    print(sfa.get_sfa_results())
Да, спасибо забыл убрать

2023-11-15 07:06 UTC, rufmus23 approved these changes

2023-11-15 09:27 UTC, merged